config:
  resourceFilters:
    - "[*,*,status]"
    - "[*,kyverno,*]"
    - "[*,kube-system,*]"
    - "[*,argocd,*]"
    - "[*,ingress-nginx,*]"
    - "[*,monitoring,*]"
    - "[*,cert-manager,*]"
    - "[*,cloudflare,*]"



